### PR TITLE
Replace literal tab with printf '\t'

### PR DESCRIPTION
**Pull request by moogle19**
Replaced the literal tab with @pr1ntf '\t'

@mariusvw Is this a better solution?

### CODE REVIEW

**Comment by mariusvw** [comment]
@moogle19 for now it seems to be a better solution. Maybe add a ioh-common file which contains ioh variables like this so the printf does not have to be run every time but only once at the startup of iohyve.

Let me know what you think about this in general, might be useful to clear out duplicate code on other places too.

**Comment by moogle19** [comment]
Yes, cleaning up the duplicate code would be create and future changes would be easier.
For example:
`local dataset="$(zfs get -H -s local -o name,value iohyve:name | grep "    $name$" | cut -f1)"`
gets called in almost every function in 'ioh-guest'.

I will open a new issue regarding that.

**Comment by mariusvw** [comment]
Ok, if you create the issue I'll try to finish my changes today and try to separately add this file to clean up some code.

**Comment by pr1ntf** [comment]
This PR has conflicts.

**Comment by moogle19** [comment]
Conflicts resolved!

**Comment by pr1ntf** [comment]
Huzzah!

**Pull request merged**
