### PR TITLE
PCI passthru on 11-Current

### PR DESCRIPTION
**Pull request by murf0**
For pci passthru on 11-Current
-S is required for both bhyveload and bhyve (You'll get "Unable to setup memory (17)" from bhyve)
-A -H -P as args for bhyve is removed when setting "iohyve set <image> bargs="-S"" They are required for APIC (Well -A atleast for APIC)

"should" not affect 10.2 since testing for -S in bargs before adding argument.

Please test and comment, feedback greatly appreciated.

### CODE REVIEW

**Comment by murf0** [comment]
I realize i try to fix 2 things in a single pull request. Bad form ish..
Also The bargs -H -A -P addition will affect 10.2.

**Comment by pr1ntf** [comment]
I like the wired memory stuff, how are you testing this? (What are you passing through?)

I don't quite follow what's going on here: https://github.com/pr1ntf/iohyve/pull/86/files#diff-d1dda53d98a3ce6903e6eac254cd2347R807

Is that related to the wired memory?

**Comment by pr1ntf** [comment]
`-S` is added only if it's not in `bargs`? Cool.

If it's not needed, it outputs nothing. Cool. 

You just scare me with the wording "Also The bargs -H -A -P addition will affect 10.2."

**Comment by murf0** [comment]
My goal was to use passthru with an em network card (4 interfaces) and I'm on 11 current. "-S" is required according to the wiki https://wiki.freebsd.org/bhyve/pci_passthru, the network card shows up after the change.

```
iohyve create pfsense 8G
iohyve set pfsense ram=2048mb
iohyve set pfsense cpu=2
iohyve set pfsense pcidev:7=passthru,10/0/0
iohyve set pfsense pcidev:8=passthru,10/0/1
iohyve set pfsense pcidev:9=passthru,9/0/0
iohyve set pfsense pcidev:1=passthru,9/0/1
iohyve set pfsense os=pfsense
iohyve set pfsense bargs="-S"
iohyve install pfsense pfSense-LiveCD-2.2.6-RELEASE-amd64.iso
```

The -S is only added to the bhyveload (or grub-bhyve) command if it is present in bargs (Without the other arguments in bargs) Since it is the only argument that needs to be present in both the bhyveload and bhyve command. 

Regarding the -H -A -P:
It is not related to the wired memory.
If the user manually sets bargs (ex. via "iohyve set pfsense bargs="-S"") it currently removes the standard bargs set at creation time here: https://github.com/pr1ntf/iohyve/blob/master/iohyve#L422
The change makes so that these arguments are always added. (ie if the user sets bargs="-S" the actual real bargs is "-A -H -P -S") Which might not be the desired action from the user, who may want to unset the standard bargs. I'm now convinced that that was a bad idea, documenting the bargs feature is a better approach. _I've removed the code doing the automatic inclusion._
I made the discovery when adding -S to bargs and was surprised that no ACPI was available when i set bargs manually preventing med from booting pfsense.

**Comment by pr1ntf** [comment]
Thanks for the update! Yeah, you can just enter `iohyve set pfsense barg ="-A -H -P -S"` because of the way it's handled by the script. IE: you can add a property to `bargs`, you need to tell `iohyve` what all the `bargs` are each time you set it. 

As for the wired memory, it'll get tested here when I get something passed through.

**Comment by pr1ntf** [comment]
I did some work to the `load` function tonight that totally broke this PR. :(

I'm sorry. :octopus:

**Comment by murf0** [comment]
Unbroken :)
I'll test it more today and report back.
Initially it works on 11-Current for me.

**Comment by pr1ntf** [comment]
I'm having problems getting my SD/MMC reader passed through to anything on my 11.0-CURRENT install. Possibly user error, still tracking down. 

HOWEVER, I no longer get the "wired memory" error when using your patch.

**Comment by pr1ntf** [comment]
HUZZAH. 

It's working for me. 

```
root@:~ # ifconfig -l
vtnet0 ix0 lo0
```

**Comment by murf0** [comment]
=) awesome!

**Pull request merged**
