### PR TITLE
Fix handling of '-r' option in 'clone' and removed '-c' option

### PR DESCRIPTION
**Pull request by moogle19**
The '-r' option was not handled correctly in 'clone'.
Also the '-c' option in 'clone' is not implemented, so I removed it from the documentation.

### CODE REVIEW

**Comment by pr1ntf** [comment]
Thanks for cleaning out the lint here!

**Comment by EpiJunkie** [comment]
Going through the code, this PR probably needs to reverted and documentation added. Looking at the code, `-r

**Comment by EpiJunkie** [comment]
Going through the code, this PR probably needs to reverted and documentation added. Looking at the code, `-r` replicates and while `-c` is not referenced I think it implies the action is to clone. The difference being `-r

**Comment by pr1ntf** [comment]
Did you get sorted out @EpiJunkie ?

**Comment by EpiJunkie** [comment]
Yea, sorry. I was mistaken and did not intend to send the message. I think it was sent twice accidently. I was having a helluva time with my keyboard that night.

**Pull request merged**
