### PR TITLE
Enhancement - provide accurate feedback when invalid command is used.

### PR DESCRIPTION
**Pull request by Tom-Fawcett**
The commit 991a0af tries to solve the issue where the user is given no feedback when they enter a invalid command. It also solves the issue where a user might be given incorrect feedback in the form of being told a invalid command will work if they are root.

9124c44 and 3e6fa03 are small fixes to 991a0af.
## Before:

User is first told that their faulty command will run if they are root:
`tom@freenas:~ % iohyve isorename`
`The isorename command needs root credentials!`

Trying sudo doesn't help (unsurprisingly) but user is given no indication of what happened: 
`tom@freenas:~ % sudo iohyve isorename`
## After:

User is told their command is faulty and offered help:
`tom@freenas:~ % iohyve isorename`
`'isorename' is not a valid command!`
`Try 'iohyve help' for more info.`

Present functionality of informing when root is needed is retained:
`tom@freenas:~ % iohyve renameiso`
`The renameiso command needs root credentials!`

### CODE REVIEW

**Comment by pr1ntf** [comment]
There's been some changes done to the script recently, including the naming and removal of some functions. There are also conflicts with this PR. If you can fix it, I'll test it and give it the good ol' merge.

**Comment by EpiJunkie** [comment]
Tom to resolve the conflicts you will need to:

Define where upstream is:
`git remote add upstream https://github.com/pr1ntf/iohyve.git`

Change to your fork's master branch:
`git checkout master`

Get the changes that 0.7.5 brought:
`git fetch upstream`

Merge your fork's master with upstream master:
`git merge upstream/master master`

Switch to your fix's branch:
`git checkout verifyCommandv2.enh`

Merge the difference between your fix branch and master.
`git merge master`

This is where the conflict will reveal itself. Git will output the files which are different. In this case, only the "`iohyve`" file has a conflict. Then you will open `iohyve` with your favorite editor and look for conflict markers. These lines start with "<<<<<<< HEAD", use "=======" as a separator, and use ">>>>>>> master" to mark the end of the conflict. You will recognize HEAD as your proposed changes and master is the upstream code. Make the necessary changes. Then a `git commit -a -m "Merge with upstream 0.7.5"`

See here for more information on code conflicts.
https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/

**Comment by EpiJunkie** [comment]
You may also consider renaming the function from `__readonly_cmd` to `__root_req_cmd`.

**Comment by Tom-Fawcett** [comment]
@pr1ntf 69cebe8 should fix the incompatibility, please tell me if there are any issues :)

Thanks @EpiJunkie for the advice. 

I believe my classification of commands is correct, though perhaps "disks" doesn't need root?

**Comment by pr1ntf** [comment]
Thank you for your work!

**Comment by EpiJunkie** [comment]
Thanks Tom, this was better than the solution I had been testing in my dev branch.

**Pull request merged**
