### PR TITLE
Fix deletion of partly matching datasets

### PR DESCRIPTION
**Pull request by moogle19**
The delete command deleted partly matching dataset, for example
ISOs with the same name as the guest.
Changed it to exactly match the guestname.

### CODE REVIEW

**Comment by pr1ntf** [comment]
Please note that if I am currently testing your PR #142 first. If that does get merged, you will have to move this into the library.

**Comment by moogle19** [comment]
Yes, I am aware of that. No problem.

**Comment by pr1ntf** [comment]
Switch has been made, conflicts must be resolved. :octopus:

**Comment by moogle19** [comment]
Resolved the conflicts.

**Comment by pr1ntf** [comment]
Thanks for all your work!!! Lookin good!

**Pull request merged**
