### PR TITLE
Fix: Use intended dataset when a 2nd $name exist.

### PR DESCRIPTION
**Pull request by EpiJunkie**
This resolves an issue where the wrong data (parameters &
disk image) is used when a duplicate `$name` dataset exists
on the system. This patch fixes the issue by grepping for
`iohyve/$name` rather than `$name`. This was observed to happen
when the same dataset as `$name` exists on system (2 or more pools)
and when the non-intended pool is alphabetically before the
intended pool. This was first observed when starting and setting
properties.

For a demonstrated example of problem:

```
root@bhost:~ # zfs list -o name -r | grep bguest
apool/backuphyve/bguest
apool/backuphyve/bguest/disk0
zpool/iohyve/bguest
zpool/iohyve/bguest/disk0
root@bhost:~ # iohyve start bguest
root@bhost:~ # zfs destroy -r apool/backuphyve/bguest/disk0
cannot destroy 'apool/backuphyve/bguest/disk0': dataset is busy
root@bhost:~ # zfs destroy -r zpool/iohyve/bguest/disk0
root@bhost:~ #
```

In this drastic example above (before this patch), `bguest` would
start using the parameters from dataset `apool/backuphyve/bguest`
and the disk image from `apool/backuphyve/bguest/disk0`. This is
further demonstrated by the ability to destroy `zpool/iohyve/bguest/disk0`.

It makes sense to use iohyve/$name for active guests so that
a replicated copy can exist on the same system without interference.
This should not interfer with multiple pool configurations. This is fairly
consistent with much of the code that is already written.

### CODE REVIEW

**Comment by EpiJunkie** [comment]
(Sorry my last PR was deleted due to me renaming it, did not realize it
would delete it. Thank you for your patience while I learn this.)

On my particular system, I have a SSD based pool which I run my `iohyve`
guests from. On a seperate, harddrive based pool, I keep a replicated copy
via `zfs send | zfs recv`. Without this patch, the backup data was being
used instead. I think it is a reasonable to assume that datasets containing
`iohyve/$name` will be the actual intended target.

**Comment by Freaky** [comment]
This looks insufficient - what if you were using "backup/iohyve" instead of "backuphyve"?

I guess even if you fixed it something else in iohyve would break :/

**Comment by EpiJunkie** [comment]
Good thought. 

[My other PRs](https://github.com/pr1ntf/iohyve/pulls/EpiJunkie) try to address the outliers. I am running all these [PRs here on this branch](https://github.com/EpiJunkie/iohyve/tree/ej-devel), it is stable and I am using it daily to manage my guests.

Does documentation need to be written that explicitly states something to the following effect?:

> "Guests under `$pool/iohyve/` are considered active. Datasets containing "iohyve" either partially or deeper in the tree can cause unpredictable behavior. If you value your data, please use a different name other than "iohyve" for your non-active iohyve datasets."

Due to the heavy use of `cut -f#` and that many of the commands that execute reference to a hard `$pool/iohyve/$name`, `/iohyve/$name`, or `/iohyve/$pool/name`, it is really not possible without a rewrite to use the word "iohyve" on datasets that are not active.

Do you have a particular command and output demonstrating this issue?

**Comment by pr1ntf** [comment]
iohyve deleting things it doesn't own is very bad. 
I also feel like this would break installations that support multiple pools. 
Surely we can work something out.

**Comment by EpiJunkie** [comment]
I do not follow.

I did not have a problem with `iohyve` deleting the wrong data, it was using the wrong disk volumes that were intended for backups. My demonstration with `zfs destroy` was to show that the wrong datasets were in use. As the guest was for testing I did not lose anything. However, output from `ps` probably would have been better.

**Comment by pr1ntf** [comment]
Sorry, after actually **looking** at the code you submitted, I see what you are saying now. (Has conflicts, by the way)

iohyve touching datasets it doesn't own is bad, no matter deletion or starting. 
I still wonder if a guest is set up on a secondary iohyve pool, will it still start with your PR? 
If you fix the conflicts, I can double check on a two-pool iohyve install.

**Comment by EpiJunkie** [comment]
Okay, I figured out the conflict. This week has been quiet a learning curve from never using a version control system.

This PR does work with multiple pools correctly as long as duplicate $names do not exist. I have tried `start/stops/destroys` without a problem. Duplicate guest names on different pools is a problem that [I briefly go into here in the commit comments](https://github.com/pr1ntf/iohyve/pull/130/commits/0548ceb9acb4bcf62956b0879eba02cd8aea1124). This PR does not address it.

Using PR #130 you can see which pool the guest is on which is helpful. #130 also makes it apparent why duplicate $names are a bad thing, which is actually a good thing to have because then people can see it and begin to fix it. Before there was not really output that made it easy to understand without having a complete understanding of all the elements working together.

**Comment by pr1ntf** [comment]
I'll give this a test on a multiple pool setup of iohyve and report back. Thanks for the hard work!

**Comment by pr1ntf** [comment]
This PR has conflicts as well now too. 
I'll slow down on the contributions for a time. 

:octopus:

**Comment by EpiJunkie** [comment]
Code conflicts resolved.

**Comment by pr1ntf** [comment]
Wubalubadubdub

**Pull request merged**
