### PR TITLE
enable set -x for debugging when requested

### PR DESCRIPTION
**Pull request by sonnens**
Would make it much easier to modify if you could toggle set -x easily.

### CODE REVIEW

**Comment by pr1ntf** [comment]
How should we go about documenting this? Should we add it to the man page or just a snippet in the readme?

**Comment by skarekrow** [comment]
I documented this by showing `-v` before every command in the man pages and `ioc-help` lib.

**Comment by sonnens** [comment]
@skarekrow I am not sure what you mean by that.

@pr1ntf I'm inclined to stuff it in README since it's a purely developer function

**Comment by pr1ntf** [comment]
I think he meant something about using a flag, which you don't use, as it's an environment variable, yes?

Readme is good, but I think in that case we can just add a page to the wiki about debugging.

**Pull request merged**
