### PR TITLE
Implemented (c)arbon clone or (r)eplicate functionality and updated h…

### PR DESCRIPTION
**Pull request by MichaelAronsen**
…elp and docs

### CODE REVIEW

**Comment by pr1ntf** [comment]
I got around to looking at this today. 

This looks good, however, we've made some changes to the man page since your latest snapshot of iohyve. Also note, you can run [this](https://gist.github.com/pr1ntf/a1fc43d8d2b12f3b28b4) one-liner to create `iohyve.8` so you just have to edit `iohyve.8.txt`.

:+1:

**Comment by pr1ntf** [comment]
We didn't want to leave you behind in the dust so I manually added your changes instead of fixing the conflicts. I credited your user name `MichaelAronsen` in the commit messages so folks know it's your stuff. 

Thanks for your work!

**Comment by MichaelAronsen** [comment]
Thanks a lot, sorry I didn't get around to it before, work is keeping me
way busy :-/

Keep up the good work!

On Wed, 3 Feb 2016 at 03:15 pr1ntf notifications@github.com wrote:

> We didn't want to leave you behind in the dust so I manually added your
> changes instead of fixing the conflicts. I credited your user name
> MichaelAronsen in the commit messages so folks know it's your stuff.
> 
> Thanks for your work!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pr1ntf/iohyve/pull/99#issuecomment-178959742.
> 
> ## 

Regards,
Michael

**Comment by pr1ntf** [comment]
No worries!

The struggle is real.

**Pull request closed without merging**
