### PR TITLE
add support for archlinux

### PR DESCRIPTION
**Pull request by Subito**

### CODE REVIEW

**Comment by pr1ntf** [comment]
This seems to work for me. 
I can boot just into the arch ISO. 

Thanks for you work!

**Comment by pr1ntf** [comment]
Also, if you have a twitter handle let me know so I can add it to the credits file if you like.

**Comment by pr1ntf** [comment]
Also, also, would you care if I changed the os type to `arch` instead of `archlinux`?

**Comment by Subito** [comment]
I wanted to call it "arch" but thought it might confuse someone with the architecture. Please call it arch, if you see fit. Twitter handle would be @svbito, thanks!

**Pull request merged**
