### PR TITLE
Refactor and Expand UEFI code

### PR DESCRIPTION
**Pull request by murf0**
Updated the UEFI code to align more with normal boot-code.
Fixed multiple taps for UEFI
Fixed ISO to only be used when using install
Removed duplicate code.
Added sectorsize as setting instead of hardcoding to 512 for UEFI.

Request for feedback, I have most certainly missed or changed something that does not align to the project.

### CODE REVIEW

**Comment by CoolmanCZ** [comment]
Hi,

There is not `Fixed multiple taps for UEFI` relevant code in the PR. Is the PR complete? Or have I missed something?

BR, Radek

**Comment by murf0** [comment]
The `pci="$(__guest_prepare $name)"` takes care of and returns all tap devices (as well as other standard devices) assigned to the guest. So instead of doing something custom for the UEFI code I reused an already existing function for that exact purpose. It looked like the correct solution.
I tested with multiple tap devices and got `bhyve -c 2 -H -w -m 8G -s 0,hostbridge -s '1,ahci-hd,/dev/zvol/zroot/iohyve/win10/disk0,sectorsize=512' -s 2,virtio-net,tap5 -s 3,virtio-net,tap6 -s '4,fbuf,tcp=0.0.0.0:5900,w=800,h=600,wait' -s 5,xhci,tablet -s 31,lpc -u -l com1,/dev/nmdm1A -l bootrom,/iohyve/Firmware/BHYVE_UEFI.fd/BHYVE_UEFI.fd ioh-win10`as the bhyve command,  (And the guest started with multiple tap-devices)

**Comment by CoolmanCZ** [comment]
Hi,

You are right. I overlooked this part `local pci_args=$(__guest_get_bhyve_cmd "$pci" )`

BR, Radek

**Comment by murf0** [comment]
=) Awesome! Thanks for looking over the code! I appreciate it.
Br
Mikael

**Comment by pr1ntf** [comment]
Looking good! This will probably be merged soon! 

I am looking to boot from ISO even if not installing, as that is the only way to get Linux UEFI guests to boot after installation (and destroying). Booting a "rEFInd" ISO before the zvol fixes this as suggested by @EpiJunkie on the mailing list. 

I also heard that this should be fixed sooner than later, so we'll just cross that bridge when we come to it.

**Comment by murf0** [comment]
Awesome!
You should be able to boot from an attached CD just using the install command, and then use the select boot medium uefi hotkey and select CD.

**Comment by pr1ntf** [comment]
I'm going to merge, but we might make a few changes. If a ZFS property (like an `iohyve` property) is not set, it is returned with a value of `-`, not an empty string. Also, instead of failing, if no sectorsize property is present, we should simply not set one. (This feature is only needed by some older Windows versions).

**Pull request merged**
