### PR TITLE
Manpage fixes

### PR DESCRIPTION
**Pull request by bsdlme**

### CODE REVIEW

**Comment by moogle19** [comment]
Looks good, but please look at [Creating a man page](https://github.com/pr1ntf/iohyve/wiki/Creating-a-man-page) and make your changes in the iohyve.8.txt

**Comment by bsdlme** [comment]
Thanks, will do!

**Comment by pr1ntf** [comment]
This is way too huge to implement all at once. If you'd prefer not to open separate PR's for each new change I can save your diff and go over the changes another time. I'd hate to see all that work go to waste.

**Comment by bsdlme** [comment]
I think the most important part of it is that [ -z $foo ] needs "" around the variable name. If you don't use "" and the variable is empty you get an error. That prevents a lot of errors when you run iohyve without the right amount of arguments.

**Pull request closed without merging**
