### PR TITLE
Small cleanup

### PR DESCRIPTION
**Pull request by moogle19**
Changed some `[ ! -z $x ]` to `[ -n "$x" ]` and reduced program calls in some places.

### CODE REVIEW

**Comment by pr1ntf** [comment]
Your `zfs set` cleanup breaks the creation of guests on my machines. Is this the case for you?

**Comment by pr1ntf** [comment]
I have reverted that part for now.

**Comment by moogle19** [comment]
Okay. What failure do you get?
 I will look at it tomorrow.

**Comment by pr1ntf** [comment]
I added a few properties, but the tail end of the output of `sudo sh -x iohyve create deb 4G` was:

```
+ echo 'Creating deb...'
Creating deb...
+ zfs create zroot/iohyve/deb
+ zfs create -V 4G -o 'volmode=dev' zroot/iohyve/deb/disk0
+ zfs set 'iohyve:name=deb' 'iohyve:size=4G' 'iohyve:ram=256M' 'iohyve:cpu=1' 'iohyve:tap=tap7' 'iohyve:con=nmdm7' 'iohyve:persist=1' 'iohyve:boot=0' 'iohyve:loader=bhyveload' 'iohyve:os=default' 'iohyve:description=Wed Jun  8 09:34:25 MDT 2016' 'iohyve:bargs=-A_-H_-P' 'iohyve:vnc=no' 'iohyve:vnc_ip=127.0.0.1' 'iohvye:vnc_port=5900' 'iohyve:vnc_w=800' 'iohyve:vnc_h=600' 'iohyve:vnc_wait=NO' 'iohyve:vnc_tablet=NO' zroot/iohyve/deb
cannot open 'iohyve:size=4G': invalid dataset name
cannot open 'iohyve:ram=256M': invalid dataset name
cannot open 'iohyve:cpu=1': invalid dataset name
cannot open 'iohyve:tap=tap7': invalid dataset name
cannot open 'iohyve:con=nmdm7': invalid dataset name
cannot open 'iohyve:persist=1': invalid dataset name
cannot open 'iohyve:boot=0': invalid dataset name
cannot open 'iohyve:loader=bhyveload': invalid dataset name
cannot open 'iohyve:os=default': invalid dataset name
cannot open 'iohyve:description=Wed Jun  8 09:34:25 MDT 2016': invalid dataset name
cannot open 'iohyve:bargs=-A_-H_-P': invalid dataset name
cannot open 'iohyve:vnc=no': invalid dataset name
cannot open 'iohyve:vnc_ip=127.0.0.1': invalid dataset name
cannot open 'iohvye:vnc_port=5900': invalid dataset name
cannot open 'iohyve:vnc_w=800': invalid dataset name
cannot open 'iohyve:vnc_h=600': invalid dataset name
cannot open 'iohyve:vnc_wait=NO': invalid dataset name
cannot open 'iohyve:vnc_tablet=NO': invalid dataset name
+ exit
```

**Comment by pr1ntf** [comment]
The `zfs` manpage says that this is a legal way to set properties, too.

**Comment by pr1ntf** [comment]
Can you set multiple properties? Because I cannot seem to even manually set multiple properties. It will set the first one just fine. 

```
pr1ntf@:~/iohyve % sudo zfs set iohyve:size=1G iohyve:ram=256 iohyve:cpu=2 zroot/iohyve/wut
cannot open 'iohyve:ram=256': invalid dataset name
cannot open 'iohyve:cpu=2': invalid dataset name
```

If not we may have found a bug in `ZFS`. Neat.

**Comment by skarekrow** [comment]
Check iocage's implementation  out. We do that for our jail creation.

**Comment by pr1ntf** [comment]
HEY YOU LANDED. Get the university and help me hack it out.

**Comment by pr1ntf** [comment]
Are you talking about [this](https://github.com/iocage/iocage/blob/master/lib/ioc-common#L63)?

You're just doing a loop, not setting multiple properties at once like the zfs [man page](https://www.freebsd.org/cgi/man.cgi?zfs%288%29) says you can. 

In the future we want to [do that](https://github.com/pr1ntf/iohyve/wiki/General-Path-to-1.0#077-goals), but this is just a temp fix and speed up.

**Comment by skarekrow** [comment]
No I'm talking about develops tree. Yes I landed :D check your text man!

**Comment by pr1ntf** [comment]
.....that's still a [loop](https://github.com/iocage/iocage/blob/develop/lib/ioc-configure#L119).

**Comment by skarekrow** [comment]
[This](https://github.com/iocage/iocage/blob/33effc776fd8668d2d5fc31ebdd199cd62a6de14/lib/ioc-configure#L96) line is what I'm talking about. Basically you're missing `-o THING=THING`.

**Comment by skarekrow** [comment]
Wrong spot amigo ;) Latest develop uses UCL not ZFS. This is an older code I linked above.

**Comment by pr1ntf** [comment]
.....Still a [loop](https://github.com/iocage/iocage/blob/33effc776fd8668d2d5fc31ebdd199cd62a6de14/lib/ioc-configure#L14) of setting properties, not setting multiple properites in one `zfs set` command. 

Putting `-o` in the command doesn't help, it still breaks, saying `-o` is not needed.

**Comment by skarekrow** [comment]
No, I'm talking about using an `eval`. Not a loop. But the important bit of this only working on dataset creation slipped my mind! So nvm!

**Comment by pr1ntf** [comment]
Eventually that will be useful for dealing with a defaults file for guest creation time. (I was planning on ~~stealing~~ "reimplementing" iocage's anyway) :wink:

**Comment by skarekrow** [comment]
~~You sonofa~~ Oh! That's great!

**Comment by pr1ntf** [comment]
Interesting finding: this happens on only some machines.

**Comment by skarekrow** [comment]
So minus my complete derpage, I also tested the failed output Trent posted above and like he said, it seems to work on some machines. I can't replicate the failure on any fresh ones, so I'm hoping this is a red herring.

**Comment by moogle19** [comment]
Ok. I found the reason it doesn't work on some machines. 

FreeBSD 10.2:
     `zfs set property=value filesystem|volume|snapshot...`
FreeBSD 10.3;
     `zfs set property=value [property=value]...    filesystem|volume|snapshot...`

Setting multiple properties at once is only supported in >= 10.3. 
Sorry, I didn't check that :see_no_evil:

**Comment by moogle19** [comment]
But as @skarekrow said, we can move the properties into the `zfs create` command with the `-o` option, where multiple properties are supported (since FreeBSD 7.0, I just checked the manpage to be sure 😉).

**Comment by pr1ntf** [comment]
_updates my machine_

**Pull request merged**
