### PR TITLE
Move functions from 'iohyve' into lib folder

### PR DESCRIPTION
**Pull request by moogle19**
Moved functions from iohve into a lib folder with files named after
the rough topic of the functions.
This should help when searching specific functions and general overview.

Still a big commit, but I basicly changed nothing in the script, just rearranged the functions.
The shift to the library would be very nice, because it really helps with overview.

### CODE REVIEW

**Comment by pr1ntf** [comment]
Awesome work! 

This has been in the [plan](https://github.com/pr1ntf/iohyve/wiki/General-Path-to-1.0#09-goals) for a long time now. I'll get to testing hopefully this weekend. 

How extensively have you tested this?

**Comment by moogle19** [comment]
Not that extensive. Have it running on a testing machine at work and on my laptop at home, where I experiment with some Windows  guests. But there it works without problems.

**Comment by pr1ntf** [comment]
Haven't forgotten about this. Been testing on and off for a few days while working on other projects. Looking good so far. 

Do you pinky promise to stick around and help out if this gets merged and something breaks because of it down the line?

**Comment by pr1ntf** [comment]
I'll keep my tax returns off of GitHub, though. 

:money_with_wings:

**Comment by pr1ntf** [comment]
Looking good though! Thanks for you work!

Hopefully nothing has slipped through the cracks.

**Pull request merged**
